### ISSUE TITLE
Multiples problems: Middleman 4 and Foundation 6.

### ISSUE THREAD

**Issue by lorraineS** [paperdigits/middleman-foundation-6#8]

**Comment by paperdigits** [comment]
Everything going OK?

**Comment by lorraineS** [comment]
Oh, thanks.

I've multiples problems,  but let's start at the beginning.

1 - For start, i can't initialize **Middleman 4** with your '**MM4 branch**'.

`middleman init -T paperdigits/middleman-foundation-6/tree/mm4 Project_name `doesn't work because middleman add .git after the URL:

`Git clone command failed. Make sure git repository exists: https://github.com/paperdigits/middleman-foundation-6/tree/mm4/.git`

2 - If i try your normal branch with Middleman 3, after the "bundle exec middleman" i have many errors. Can be linked to my Ruby version (2.4.0).

```
$ bundle exec middleman
Expected string default value for '--instrument'; got false (boolean)
Expected string default value for '--reload-paths'; got false (boolean)
Expected string default value for '--instrument'; got false (boolean)
== The Middleman is loading
/Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:17:in `require': /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap.rb:38: syntax error, unexpected keyword_do_block, expecting '}' (SyntaxError)
          layout: proc do |file, sitemap_app|
                         ^
/Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap.rb:38: syntax error, unexpected '|', expecting '='
t: proc do |file, sitemap_app|
                              ^
/Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap.rb:41: syntax error, unexpected '}', expecting keyword_end
        }, 'Callbacks that can exclude 
         ^
/Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/sitemap.rb:76: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:17:in `<top (required)>'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:124:in `require'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:124:in `new_app'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:31:in `start'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/cli/server.rb:89:in `server'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:29:in `run'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:126:in `run'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
	from /Users/Name/.rvm/gems/ruby-2.4.0/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
	from /Users/Name/.rvm/gems/ruby-2.4.0/bin/middleman:22:in `load'
	from /Users/Name/.rvm/gems/ruby-2.4.0/bin/middleman:22:in `<main>'
	from /Users/Name/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Name/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by paperdigits** [comment]
1. This isn't the correct way to clone a branch. I'm not sure if it'll work with the middleman command, but you can clone the `mm4` branch to your local machine using `git clone -b <branch> <remote_repo>` and then use middleman to create a new project. 

You can use `middleman init MY_PROJECT_FOLDER -T file:///path/to/local/repo/`

2. I haven't tried with ruby 2.4, my current sites are all running 2.1. I'll see if it works for me with ruby 2.4 using middleman 3.

It's probably time to promote the `mm4` branch to master; I was waiting for one of the gems to be out of beta, but that was a while ago. I was waiting for `middleman-sprockets` to be a final release instead of an RC and I see that's happened now. I'll try and update it when I have time.

**Comment by lorraineS** [comment]
You use what version of Middleman? I switched to 2.1, but middleman core requires ruby> 2.2.0.

**Comment by paperdigits** [comment]
I've got a Gemfile.lock that is pretty old, so I'm sure I'm behind on the current version.

I'm still on version 3 of middleman.
